name: Bug Report
description: Report a problem in the strichliste-rs
labels: [bug]
title: "[BUG] "
body:
  - type: checkboxes
    id: latestversions
    attributes:
      label: Latest Versions
      options:
        - label: I confirm I am using the latest strichliste version
          required: true
  - type: input
    attributes:
      label: "strichliste-rs Version"
      placeholder: "strichliste-rs --version"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        * Step 1
        * Step 2
        * ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      placeholder: |
        Describe the behavior you expect.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behavior"
      placeholder: |
        Describe the actual behaviour.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional information"
    validations:
      required: false
  - type: checkboxes
    id: Duplicate
    attributes:
      label: Avoiding Duplicates
      options:
        - label: I checked existing open and closed issues and PRs to see if this issue is already known
          required: true
