name: Feature Request
description: Request a new Feature that strichliste-rs should provide
labels: feature
title: "[FEAT] "
body:
  - type: textarea
    attributes:
      label: Description
      description: Description of the Feature you are planning to implement
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: |
        The Impact to the existing code. The change ...
      options:
        - is a gradual refactoring that can be applied in steps
        - is an entire refactoring that can NOT be applied in steps
        - is contained to a small area
        - touches almost the entire frontend
        - touches almost the entire backend
        - touches almost the entire frontend + backend
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Implementation
      description: Implementation
      options:
        - label: I am willing to implement this myself
  - type: checkboxes
    attributes:
      label: |
        If the change is a big change that can be applied incrementally:
      options:
        - label: I will implement it incrementally in a single PR, each incremental step in a commit
        - label: I will implement it incrementally in multiple PRs
  - type: checkboxes
    id: Duplicate
    attributes:
      label: Avoiding Duplicates
      options:
        - label: I checked existing open and closed issues and PRs to see if this is already in Progress or has been discussed already
          required: true
